### ISSUE TITLE
'Table 'piwigo.image_videojs' doesn't exist' after upgrading to 2.9b

### ISSUE THREAD

**Issue by jradwan** [xbgmsharp/piwigo-videojs#131]
After upgrading to 2.9b I get this error whenever I try to view a video:

```
Fatal error: Uncaught --> Smarty: Unable to load template file '/usr/local/piwigo/plugins/piwigo-videojs/template/vjs-player.tpl.v5' <-- thrown in /usr/local/piwigo/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139

Warning:  [mysql error 1146] Table 'piwigo.image_videojs' doesn't exist
SELECT * FROM image_videojs WHERE `id`=47713; in /usr/local/piwigo/include/dblayer/functions_mysqli.inc.php on line 845


Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in /usr/local/piwigo/include/dblayer/functions_mysqli.inc.php:226 Stack trace: #0 /usr/local/piwigo/plugins/piwigo-videojs/main.inc.php(83): pwg_db_fetch_assoc(false) #1 /usr/local/piwigo/include/functions_plugins.inc.php(229): vjs_format_exif_data(Array, '././galleries/p...', Array) #2 /usr/local/piwigo/include/functions_metadata.inc.php(161): trigger_change('format_exif_dat...', Array, '././galleries/p...', Array) #3 /usr/local/piwigo/include/picture_metadata.inc.php(39): get_exif_data('././galleries/p...', Array) #4 /usr/local/piwigo/picture.php(1031): include('/usr/local/piwi...') #5 {main} thrown in /usr/local/piwigo/include/dblayer/functions_mysqli.inc.php on line 226
```

Looks like the filename is wrong. It's looking for a filename ending in .v5 but the filenames I have look like 'vjs-5-player.tpl'. Plus the missing table which I don't see in my database.

**Comment by jradwan** [comment]
Thank you, that resolved the issue.
